export const categoryMap=new Map()
categoryMap.set('儿童亲子',0)
categoryMap.set('演唱会',1)
categoryMap.set('音乐会',2)
categoryMap.set('话剧歌剧',3)
categoryMap.set('舞蹈芭蕾',4)
categoryMap.set('曲苑杂坛',5)
categoryMap.set('体育',6)
categoryMap.set('展览休闲',7)

