spring:
#  application:
#    name: user-service
  datasource:
    url: jdbc:mysql://database:3307/ebookstore?serverTimezone=UTC
    username: root
    password: 518021911178
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://518021911178:518021911178@localhost:27017/ebookstore
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  thymeleaf:
    cache: false


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka
server:
  port: 8001
#spring.datasource.url=jdbc:mysql://localhost:3307/ebookstore?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=518021911178
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database=mysql
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.thymeleaf.cache=false
#spring.jpa.hibernate.use-new-id-generator-mappings= false
#
#spring.data.mongodb.uri=mongodb://518021911178:518021911178@localhost:27017/ebookstore

